modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/SteveKunG/Originatia/issues"
license = "MIT License"

[[mods]]
modId = "originatia"
version = "${version}"
displayName = "Originatia"
description = "A small mod that improves Origin Realms gameplay, Block Sounds fixes and more!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/originatia"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/originatia_version.json"
authors = "SteveKunG"
logoFile = "logo.png"

[[dependencies.originatia]]
modId = "forge"
mandatory = true
versionRange = "[36.1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.originatia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.originatia]]
modId = "stevekungs_lib"
mandatory = true
versionRange = "[4.1.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.originatia]]
modId = "architectury"
mandatory = true
versionRange = "[1.12,)"
ordering = "NONE"
side = "CLIENT"