modLoader="javafml"
loaderVersion="[35,)"
updateJSONURL="https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/originrealmscatia_version.json"
issueTrackerURL="https://github.com/SteveKunG/OriginRealmscatia/issues"
license="MIT License"

[[mods]]
modId="originrealmscatia"
version="1.0.0"
displayName="OriginRealmscatia"
description="Useful Mod for Origin Realms server!"
credits="Beta test"
displayURL="https://www.curseforge.com/minecraft/mc-mods/originrealmscatia"
authors="SteveKunG"
logoFile="logo.png"

[[dependencies.originrealmscatia]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.originrealmscatia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.originrealmscatia]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.originrealmscatia]]
    modId="indicatia"
    mandatory=false
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="CLIENT"